name: AirPort # & cpdaily

on:
  schedule:
    - cron: '3 3 * * *'  # 每天11点
  workflow_dispatch:

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository == 'GitCourser/actions'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: script
      - name: Run Script
        env:
          airport: ${{ secrets.AIRPORT }}
          moss: ${{ secrets.MOSS }}
          GOTIFY_CFG: ${{ secrets.GOTIFY_CFG }}
        run: |
          cd other
          # python airport.py
          python moss.py
