name: AliYunDrive

on:
  schedule:
    - cron: '1 1 * * *'
  workflow_dispatch:

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository == 'GitCourser/actions'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: script
      - name: Run Script
        env:
          PUBLIC_REPO_TOKEN: ${{ secrets.PUBLIC_REPO_TOKEN }}
          GITHUB_REPOS: ${{ github.repository }}
          ALIYUN: ${{ secrets.ALIYUN }}
          GOTIFY_CFG: ${{ secrets.GOTIFY_CFG }}
        run: |
          pip install pynacl
          cd other && python aliyundrive.py
