name: test

on:
  workflow_dispatch

jobs:
  downloading:
    runs-on: ubuntu-latest
    steps:
    # - name: Set up Python
    #   uses: actions/setup-python@v1
    #   with:
    #     python-version: 3.6
    - name: Prepare your file
      run: |
        python3 -m pip install -U yt-dlp[default]
        # mkdir bao && cd bao
        # wget https://dist.torproject.org/torbrowser/11.5.7/tor-win32-0.4.7.10.zip
        # wget https://www.torproject.org/dist/torbrowser/11.5.7/torbrowser-install-11.5.7_zh-CN.exe
        # cd ..
        # tar -zcvf bao.tar.gz bao
        mkdir download
        yt-dlp -P ./download http://www.mgtv.com/b/385724/13069162.html
        tar -zcvf down.tar.gz download
    - name: Upload your file
      run: |
        curl -sL https://git.io/file-transfer | sh
        ./transfer wss down.tar.gz
