name: test

on:
  workflow_dispatch

jobs:
  downloading:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Prepare your file
      run: |
        mkdir bao
        pip install -t bao grequests
        tar -zcvf bao.tar.gz bao
        mkdir download
        cp bao.tar.gz download
    - name: Upload your file
      run: |
        curl -sL https://git.io/file-transfer | sh
        ./transfer wet ./download/
