name: ChaoXing

on:
  schedule:
    # - cron: '0 11 * * 1-5'  # 周一到周五晚上19点
    # - cron: '0 23 * * 5,6'  # 周六周日早上7点
    # - cron: '0 5 * * 0,6'   # 周六周日下午13点
    # - cron: '0 5,23 * * *'  # 每天7、13点
    # - cron: '0 10 * * 1'  # 周一18点
    - cron: '0 23 * * 1,3'  # 周二周四7点
  workflow_dispatch:

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository == 'GitCourser/actions'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: script
      - name: Run Script
        env:
          chaoxing: ${{ secrets.CHAOXING }}
          WX_CFG: ${{ secrets.WX_CFG }}
        run: |
          pip install lxml pydes
          cd other
          python chaoxing.py
