name: ChaoXing

on:
  schedule:
    - cron: '*/5 11-13 * * 1-5'
    - cron: '*/5 0-9 * * 0,6'
    - cron: '*/5 23 * * 5,6'
  workflow_dispatch:

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository == 'GitCourser/actions'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: script
      - name: Run Script
        run: |
          date -R
          ls -l
          cd other
          python ./chaoxing.py
          python -V
