name: CI

on:
  workflow_dispatch

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: scf
      - name: Run a multi-line script
        run: |
          date -R
          ls -l
