name: CI

on:
  schedule:
    - cron: '*/8 7-9 * * *'
    - cron: '*/20 11-15 * * *'
  workflow_dispatch:

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository == 'GitCourser/actions'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: scf
      - name: Run a multi-line script
        run: |
          date -R
          ls -l
