name: Sync Repository Action

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Sync Repository
      uses: GitCourser/actions@sync
      env:
          KEY0: ${{ secrets.KEY0 }}
          KEY1: ${{ secrets.KEY1 }}
      with:
          src: ${{ secrets.SRC }}
          dst1: ${{ secrets.DST1 }}
          dst2: ${{ secrets.DST2 }}
