name: sync Python-100-Days

on:
  schedule:
    - cron: '0 0 3 * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository == 'GitCourser/actions'
    steps:
      - name: git-sync
        uses: GitCourser/git-sync@v3
        with:
          source_repo: "jackfrued/Python-100-Days"
          source_branch: "master"
          destination_repo: "GitCourser/Python-100-Days"
          destination_branch: "master"
          ssh_private_key: ${{ secrets.KEY1 }}
      - name: Sync to Gitee
        uses: GitCourser/sync-repo-to-gitee@master
        env:
          SSH_KEY: ${{ secrets.KEY1 }}
        with:
          github-repo: "git@github.com:GitCourser/Python-100-Days.git"
          gitee-repo: "git@gitee.com:Courser/Python-100-Days.git"
