name: sync git-sync

on:
  schedule:
    - cron: '0 0 2 */6 *'
  workflow_dispatch:

jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: GitCourser/git-sync@v3
        with:
          source_repo: "wei/git-sync"
          source_branch: "master"
          destination_repo: "GitCourser/git-sync"
          destination_branch: "master"
          ssh_private_key: ${{ secrets.KEY1 }}
