name: testtest

on:
  workflow_dispatch

jobs:
  downloading:
    runs-on: ubuntu-latest
    steps:
    - name: testtest
      run: |
        mkdir download
        docker pull nevinee/jd:v4
        docker exec nevinee/jd /bin/bash
        ls
        ls /
        ls /root
    - name: Upload your file
      run: |
        curl -sL https://git.io/file-transfer | sh
        ./transfer wet ./download/
