name: testtest

on:
  workflow_dispatch

jobs:
  downloading:
    runs-on: ubuntu-latest
    steps:
    - name: testtest
      run: |
        mkdir download
        docker pull nevinee/jd:v4
        docker images
        docker ps -l
        docker save nevinee/jd:v4 | gzip > download/jd.tar.gz
    - name: Upload your file
      run: |
        curl -sL https://git.io/file-transfer | sh
        ./transfer cow ./download/
