name: testtest

on:
  workflow_dispatch

jobs:
  downloading:
    runs-on: ubuntu-latest
    steps:
    - name: testtest
      run: |
        mkdir download
        docker pull nevinee/jd:v4
        docker exec 925eb6010e56 /bin/bash
        ls
        ls /
        ls /root
